import pool from "../database/db.js";

export const getAllPosts = async (req, res) => {
  try {
    const response = await pool.query(
      "SELECT * FROM posts order by created_at desc"
    );
    res.status(200).json(response.rows);
  } catch (error) {
    console.error("Error fetching posts:", error);
    res.status(500).json({ error: "Internal server error" });
  }
};
export const createPost = async (req, res) => {
  const { title, content, owner_id, collab } = req.body;
  try {
    //the post_id and created_at are auto generated by the database
    //Returning * is used to return the created post
    const response = await pool.query(
      "INSERT INTO posts (title, content, owner_id, collab) VALUES ($1, $2, $3, $4) RETURNING *",
      [title, content, owner_id, collab]
    );
    res.status(201).json(response.rows[0]);
  } catch (error) {
    console.error("Error creating post:", error);
    res.status(500).json({ error: "Internal server error" });
  }
};
export const updatePost = async (req, res) => {
  res.send("Hello World");
};
export const deletePost = async (req, res) => {
  const { post_id } = req.params;
  try {
    const response = await pool.query(
      "DELETE FROM posts WHERE post_id = $1 RETURNING *",
      [post_id]
    );
    res.status(200).json(response.rows[0]);
  } catch (error) {
    console.error("Error deleting post:", error);
    res.status(500).json({ message: "Internal server error" });
  }
};

export const getUserPosts = async (req, res) => {
  const { user_id } = req.params;
  try {
    const response = await pool.query(
      "SELECT * FROM posts WHERE owner_id = $1",
      [user_id]
    );
    res.status(200).json(response.rows);
  } catch (error) {
    console.error("Error fetching user posts:", error);
    res.status(500).json({ message: "Internal server error" });
  }
};
